name: 'Setup Lazarus'
description: 'Setup Lazarus using sourceforge installers'
inputs:
  laz-url: 
    required: true
  fpc-url: 
    required: false
runs:
  using: 'node12'
  main: 'dist/index/index.js'

